### PR TITLE
fix: Return correct source when sources share URI prefix

### LINKED ISSUE #492: GTAA lookup doesn’t work
For example https://termennetwerk.netwerkdigitaalerfgoed.nl/lookup?uri=http://data.beeldengeluid.nl/gtaa/34685

### LINKED ISSUE #604: reconcilation preview shows the wrong source
When reconciling against the NTA the preview shows the "Brinkman Trefwoordenthesaurus" as the terminology source.

### PR DESCRIPTION
**Pull request by ddeboer**
* Queries can return a `skos:inScheme` triple that will be used
  instead of the dataset matching the URI prefix.

Fix #492.
Fix #604.

### CODE REVIEW

File: packages/network-of-terms-query/src/lookup/lookup.ts [hunk 1]
```diff
@@ -69,15 +72,36 @@ export class LookupService {
...
+          }
+          termsResult.terms.push(term);
+        }
+        acc.set(dataset, termsResult);
+      } else {
+        const dataset = this.catalog.getDatasetByDistributionIri(
+          result.distribution.iri
+        )!;
+        acc.set(dataset, result);
+      }
```
Comment (ddeboer) [inline packages/network-of-terms-query/src/lookup/lookup.ts:99]: This added complexity is anything but elegant, so we may want to refactor later.
